Fazendo previsões com a inteligencia artificial!
Sempre que começar a produzir um novo codigo é necessario listar o passo a passo.
Os passo que vamos fazer são:
• Importar a base de dados
• Verificar informações vazias
• Fazer o tratamento na base de dados
• Selecionar as colunas de treino para o modelo
• Treinar 2 modelos
• Verificar o melhor modelo
• Verificar quais as características mais importantes para definir o score do cliente

In [1]:
#Importando as bibliotecas
import pandas as pd

In [6]:
#Importando as base de dados
dados = pd.read_csv("pythoninicio/clientes.csv")
display(dados)

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,alto_gasto_pagamento_medio,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,mecanico,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

In [7]:
#Verificando colunas com valores vazios
print(dados.info())
print(dados.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB
None
Index(['id_cliente', 'mes', 'idade', 'profissao', 'salario_anual',
       'num_contas', 'num_cartoes', 'juros_emprestimo', 'num_emprestimos',
       'dias_atraso', 'num_pagamentos_atrasados', 'num_verificacoes_credito',
       'mix_credito', 'divida_total', 'taxa_uso_credito',
       'idade_historico_credito', 'investimento_mensal',
       'comportamento_pagamento', 'saldo_final_mes', 'score_credito',
       'emprestimo_carro', 'emprestimo_casa', 'emprestimo_pessoal',
       'emprestimo_credito', 'emprestimo_estudantil'],
      dtype='object')

In [9]:
#Transformando colunas em texto e fazendo o tratamento
# A função from, vai fazer que a gente use só uma parte da biblioteca
from sklearn.preprocessing import LabelEncoder
# vai transformar as colunas de texto em números, ex: profissoes vai sair de cientista, professor, mecanico, etc para 0, 1, 2, etc
codificador = LabelEncoder()


# só não aplicamos na coluna de score_credito que é o nosso objetivo
for coluna in dados.columns:
    if dados[coluna].dtype == "object" and coluna != "score_credito":
        dados[coluna] = codificador.fit_transform(dados[coluna])

# verificando se realmente todas as colunas foram modificadas
print(dados.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int32
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int32
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int32
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int32(3), int64(7), object(1)
memory usage: 17.9+ MB
None

In [10]:
display(dados)

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,1,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,3,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,5,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,2,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,4,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,2,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,2,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,11,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,0,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,2,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,11,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,0,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,11,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,3,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,2,393.673696,Poor,1,0,0,0,1

In [19]:
# escolhendo quais colunas vamos usar para treinar o modelo
# y é a coluna que queremos que o modelo calcule
# x vai todas as colunas que vamos usar para prever o score de credito, não vamos usar a coluna id_cliente porque ela é um numero qualquer que nao ajuda a previsao
x = dados.drop(["score_credito", "id_cliente"], axis=1)
y = dados["score_credito"]

from sklearn.model_selection import train_test_split

# separamos os dados em treino e teste. Treino vamos dar para os modelos aprenderem e teste vamos usar para ver se o modelo aprendeu corretamente
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

modelo_arvore = RandomForestClassifier() #modelo arvore decisão
modelo_knn = KNeighborsClassifier() #modelo do KNN( nearest neighbors - vizinhos mais proximos)

#Treinando os modelos
modelo_arvore.fit(x_train, y_train)
modelo_knn.fit(x_train, y_train)

KNeighborsClassifier()

 Acurácia É uma das métricas de avaliação que
utilizamos para verificar se um modelo é bom em relação a outro.
A acurácia nada mais é do que a performance do modelo, ou seja, vai verificar quantas informações foram classificadas de forma
correta.

In [22]:
#Acuracia do modelo
#Se o nosso modelo chutasse tudo "Standar", qual seria a acuracia do modelo?
contagem_scores = dados["score_credito"].value_counts()
print(contagem_scores["Standard"] / sum(contagem_scores))

0.53174

Veja que a acurácia seria de 53%. Isso quer dizer que ele acertou 53% das classificações que fez.

Criando outro modelo de Acuracia

In [23]:
from sklearn.metrics import accuracy_score

#Calculamos as previsoes
previsão_arvore = modelo_arvore.predict(x_test)
previsao_knn = modelo_knn.predict(x_test.to_numpy())

#Comparamos as previsões com o y_test
#Esse score queremos o maior (maior acuracia, mas tb tem que ser maior do que o chute de tudo Standard)
print(accuracy_score(y_test, previsão_arvore))
print(accuracy_score(y_test, previsao_knn))

c:\Users\eloiz\Prog_eloiza\env\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

0.8256666666666667
0.7324

Para a Árvore de Decisão tivemos uma
acurácia de 82% enquanto que para o
modelo KNN tivemos 73% de acurácia.

In [26]:
#Caracteristicas importantes para definir o score de credito?
dados = list(x_test.columns)
importancia = pd.DataFrame(index=dados, data=modelo_arvore.feature_importances_)
importancia = importancia + 100
print(importancia)

                                   0
mes                       100.039357
idade                     100.042340
profissao                 100.032679
salario_anual             100.050462
num_contas                100.035800
num_cartoes               100.043809
juros_emprestimo          100.080686
num_emprestimos           100.030705
dias_atraso               100.064169
num_pagamentos_atrasados  100.045178
num_verificacoes_credito  100.043979
mix_credito               100.082107
divida_total              100.121368
taxa_uso_credito          100.050721
idade_historico_credito   100.075123
investimento_mensal       100.048460
comportamento_pagamento   100.023551
saldo_final_mes           100.054430
emprestimo_carro          100.007015
emprestimo_casa           100.007215
emprestimo_pessoal        100.006978
emprestimo_credito        100.007038
emprestimo_estudantil     100.006830

Caracteristicas mais importantes para definir o score de credito.
você pode notar que as informações de
divida_total, mix_credito e juros_empréstimo são
características bem importantes.
Então elas vão ajudar bastante na hora de definir o score do
cliente, mais do que as outra características.